Return-Path: <linux-um-bounces+lists+linux-um=lfdr.de@lists.infradead.org>
X-Original-To: lists+linux-um@lfdr.de
Delivered-To: lists+linux-um@lfdr.de
Received: from bombadil.infradead.org (bombadil.infradead.org [IPv6:2607:7c80:54:e::133])
	by mail.lfdr.de (Postfix) with ESMTPS id 4826F198A0A
	for <lists+linux-um@lfdr.de>; Tue, 31 Mar 2020 04:38:22 +0200 (CEST)
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/relaxed;
	d=lists.infradead.org; s=bombadil.20170209; h=Sender:
	Content-Transfer-Encoding:Content-Type:Cc:List-Subscribe:List-Help:List-Post:
	List-Archive:List-Unsubscribe:List-Id:MIME-Version:References:In-Reply-To:
	Subject:To:From:Message-ID:Date:Reply-To:Content-ID:Content-Description:
	Resent-Date:Resent-From:Resent-Sender:Resent-To:Resent-Cc:Resent-Message-ID:
	List-Owner; bh=O0i1Uf57XqEYnaT8a4FiB3DGq26sqotwgiWn+PDvwjg=; b=jHmJsPo6Mz1tSR
	SC5PbMl9Y4zQ3xHXLxjf2a8lRz+Fx8dU8tmnXLXhR5+UTLuw4e33iQXCqa2kO+hYhY0+P38oynafy
	kFH+MlH9QGYI+1tAehW40GZLQpI/CHiZiqFggSe/z2Giscg4MRGtIs+AQcD+iC4UorDbLb1ltInVz
	Cq8aIOKWWBwGmpcxZjPyeofxekwOJ8u/xcQBMKP9j251xEVadfYjTV0HsaO4Wlr2vM7LY/Zaxm3/T
	1vu9YrT6DJiQgLXDtnn1Gz8OTa9DqVjb2sO1gXAQFoMJ6SInqB86ruCKCQmWRRuwYFItCb9h/p9gG
	1y7Tgi0BkQvBqxw+PlqA==;
Received: from localhost ([127.0.0.1] helo=bombadil.infradead.org)
	by bombadil.infradead.org with esmtp (Exim 4.92.3 #3 (Red Hat Linux))
	id 1jJ6n9-0006s0-EI; Tue, 31 Mar 2020 02:38:15 +0000
Received: from mail-pf1-x444.google.com ([2607:f8b0:4864:20::444])
 by bombadil.infradead.org with esmtps (Exim 4.92.3 #3 (Red Hat Linux))
 id 1jJ6n6-0006r7-Ln
 for linux-um@lists.infradead.org; Tue, 31 Mar 2020 02:38:14 +0000
Received: by mail-pf1-x444.google.com with SMTP id k15so4478396pfh.6
 for <linux-um@lists.infradead.org>; Mon, 30 Mar 2020 19:38:11 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=gmail.com; s=20161025;
 h=date:message-id:from:to:cc:subject:in-reply-to:references
 :user-agent:mime-version;
 bh=flZxqn5EyqTevSwFMF7D5Y8OM06DVGUHbu2b6k5ECT8=;
 b=ECFHY/KsBUGLdilUOnq61TWd36EQLF9QGO6L3JA/Orf/2JlgmfwGjBYx+lu/uaIVgD
 oXCFbqnKsMM3iFTyb2A9lWhdho4lewUtabAoPXGjRED2H6YxG6rDvTLwatD0wyjMaLc8
 20/vB0Y3hPULCH/knsJl0/bVzqsBCWN9Q2lZ8v7QsNpo+aJMOzlGEWUR3rta8hafudRg
 3BxOaWqYsmaebA1GGtPj1hEXhgRMPCzuuR6vCzBCwJgYNg2OHmf6mYNxNEgqubt/0VLr
 AJvmhNHreP4VRQ/NZ1p1LtN+eFfKaZ8pL/DpoQKzC6uibhgkBQfKhAC458qWodxRCBsk
 RFoA==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
 d=1e100.net; s=20161025;
 h=x-gm-message-state:date:message-id:from:to:cc:subject:in-reply-to
 :references:user-agent:mime-version;
 bh=flZxqn5EyqTevSwFMF7D5Y8OM06DVGUHbu2b6k5ECT8=;
 b=pFmz4y9xU0CCdAhF5DEDt5e4Z19qepYLr4Gw5uNqSZB3MxsvTnobMab7PDvHzQnafK
 nwiLcgAPc+hLx1NcF28ocaI86h2JY+yDNYVUL7yOvh3L4xc0PP1X7kUIXZmvVcleB/an
 ng0KQ9A6LYLcYFRASPR5C74pPEovO2GK30IvAC6+94HhW/JfYlUK6yR1g/vKMVsOjXfX
 G/ehODBj8oVU93xjjwm65S6FsXvcuJtrm+Rw+kbsjNgrCUNprsCZkK70r0M0M/p1nPMA
 E66B9H0EcBjjJYjt5d6obCo8PCd3lOBEE4jRwvvES/5ye3ZCs6g7n6c9fEhUYKtj8H19
 zFZQ==
X-Gm-Message-State: ANhLgQ3WYUwCyy2wXDFffdv2HAxeGW6aR/DXxuqMwW+8zw5ms3JEFP8v
 reD4Zepmfaza6nI9aWgsJ9E=
X-Google-Smtp-Source: ADFU+vu9sUGvXVhs/m0wBHBJOjW4RloYe8cBFnrOHE9g1tqQ5bfUTM0LOFAq1hFbqPaLJR/sqhazrg==
X-Received: by 2002:aa7:8f22:: with SMTP id y2mr16234089pfr.300.1585622291086; 
 Mon, 30 Mar 2020 19:38:11 -0700 (PDT)
Received: from earth-mac.local.gmail.com
 (219x123x138x129.ap219.ftth.ucom.ne.jp. [219.123.138.129])
 by smtp.gmail.com with ESMTPSA id m68sm735095pjb.0.2020.03.30.19.38.08
 (version=TLS1_2 cipher=ECDHE-RSA-CHACHA20-POLY1305 bits=256/256);
 Mon, 30 Mar 2020 19:38:10 -0700 (PDT)
Date: Tue, 31 Mar 2020 11:38:07 +0900
Message-ID: <m25zelxn8w.wl-thehajime@gmail.com>
From: Hajime Tazaki<thehajime@gmail.com>
To: johannes@sipsolutions.net
Subject: Re: [RFC v4 23/25] um lkl: add UML network driver for lkl
In-Reply-To: <b2a730a4bcafb13cb1b29a637f8f8449cf3521d6.camel@sipsolutions.net>
References: <cover.1585579244.git.thehajime@gmail.com>
 <0f087b36ad579eeb8062b12e9e61566d9b5b18ac.1585579244.git.thehajime@gmail.com>
 <b2a730a4bcafb13cb1b29a637f8f8449cf3521d6.camel@sipsolutions.net>
User-Agent: Wanderlust/2.15.9 (Almost Unreal) Emacs/25.3 Mule/6.0
 (HANACHIRUSATO)
MIME-Version: 1.0 (generated by SEMI-EPG 1.14.7 - "Harue")
X-CRM114-Version: 20100106-BlameMichelson ( TRE 0.8.0 (BSD) ) MR-646709E3 
X-CRM114-CacheID: sfid-20200330_193812_737037_D31F86F6 
X-CRM114-Status: GOOD (  12.37  )
X-Spam-Score: -0.2 (/)
X-Spam-Report: SpamAssassin version 3.4.4 on bombadil.infradead.org summary:
 Content analysis details:   (-0.2 points)
 pts rule name              description
 ---- ---------------------- --------------------------------------------------
 -0.0 RCVD_IN_DNSWL_NONE     RBL: Sender listed at https://www.dnswl.org/,
 no trust [2607:f8b0:4864:20:0:0:0:444 listed in]
 [list.dnswl.org]
 0.0 SPF_HELO_NONE          SPF: HELO does not publish an SPF Record
 0.0 FREEMAIL_FROM          Sender email is commonly abused enduser mail
 provider [thehajime[at]gmail.com]
 -0.0 SPF_PASS               SPF: sender matches SPF record
 0.1 DKIM_SIGNED            Message has a DKIM or DK signature, not necessarily
 valid
 -0.1 DKIM_VALID_EF          Message has a valid DKIM or DK signature from
 envelope-from domain
 -0.1 DKIM_VALID Message has at least one valid DKIM or DK signature
 -0.1 DKIM_VALID_AU          Message has a valid DKIM or DK signature from
 author's domain
 0.0 TO_NO_BRKTS_FROM_MSSP  Multiple header formatting problems
 0.0 FROM_MISSP_FREEMAIL    From misspaced + freemail provider
X-BeenThere: linux-um@lists.infradead.org
X-Mailman-Version: 2.1.29
Precedence: list
List-Id: <linux-um.lists.infradead.org>
List-Unsubscribe: <http://lists.infradead.org/mailman/options/linux-um>,
 <mailto:linux-um-request@lists.infradead.org?subject=unsubscribe>
List-Archive: <http://lists.infradead.org/pipermail/linux-um/>
List-Post: <mailto:linux-um@lists.infradead.org>
List-Help: <mailto:linux-um-request@lists.infradead.org?subject=help>
List-Subscribe: <http://lists.infradead.org/mailman/listinfo/linux-um>,
 <mailto:linux-um-request@lists.infradead.org?subject=subscribe>
Cc: tavi.purdila@gmail.com, linux-kernel-library@freelists.org,
 retrage01@gmail.com, linux-um@lists.infradead.org, linux-arch@vger.kernel.org
Content-Type: text/plain; charset="us-ascii"
Content-Transfer-Encoding: 7bit
Sender: "linux-um" <linux-um-bounces@lists.infradead.org>
Errors-To: linux-um-bounces+lists+linux-um=lfdr.de@lists.infradead.org


Thanks for the comments, Johannes.

On Tue, 31 Mar 2020 06:31:15 +0900,
Johannes Berg wrote:
> 
> 
> > +++ b/arch/um/lkl/include/asm/irq.h
> > @@ -2,6 +2,9 @@
> >  #ifndef _ASM_LKL_IRQ_H
> >  #define _ASM_LKL_IRQ_H
> >  
> > +/* pull UML's definitions */
> > +#include "../../../include/asm/irq.h"
> 
> This is _really_ ugly.

Hmm, in previous patchset (until v3), I was using the worse approach
(I thought) to avoid this include.

+KBUILD_CFLAGS  += -DTIMER_IRQ=0 -DUBD_IRQ=4 -DUM_ETH_IRQ=5 -DLAST_IRQ=15

And I thought the current way is better than before.


> > +#if defined(__linux) && (defined(__i386) || defined(__x86_64))
> > +#include <os.h>
> > +#endif
> > +void *um_os_signal(int signum, void *handler);
> 
> and arguably those random declarations you're sprinkling are worse.

It means that those are only used when UML drivers (net, block) are
enabled, which are only available on Intel/linux hosts.  OTOH,
UMMODE_LIB _will_ support non-Intel/Linux hosts in the future thus,
this ifdefs exist.

> > @@ -181,6 +196,11 @@ void init_IRQ(void)
> >  	for (i = 0; i < NR_IRQS; i++)
> >  		irq_set_chip_and_handler(i, &dummy_irq_chip, handle_simple_irq);
> >  
> > +#if defined(__linux) && (defined(__i386) || defined(__x86_64))
> 
> What's with all those ifdefs with this condition?

Same as above.
but I agree that the ifdefs are cryptic; I'll try to make it more
understandable if I use ifdefs.

> > +++ b/tools/lkl/lib/um/um_glue.c
> > @@ -0,0 +1,39 @@
> > +// SPDX-License-Identifier: GPL-2.0
> > +#include <stdio.h>
> > +#include <stdlib.h>
> > +#include <string.h>
> > +#include <unistd.h>
> > +#include <errno.h>
> > +
> > +
> > +
> > +char lkl_um_devs[4096];
> > +
> > +/* from sigio.c */
> > +void maybe_sigio_broken(int fd, int read)
> > +{
> > +}
> > +
> > +/* from process.c */
> > +int os_getpid(void)
> > +{
> > +	return getpid();
> > +}
> 
> All of this really is quite ugly - are you sure it's needed for just the
> vector network driver??

Those are needed when we use UML_NET or BLK_DEV_UBD is enabled.  I was
trying to minimize those glue code as much as possible; I need another
try to check if we can remove more or eliminate completely by other
ways.

-- Hajime

_______________________________________________
linux-um mailing list
linux-um@lists.infradead.org
http://lists.infradead.org/mailman/listinfo/linux-um
